services:
  # Service 1: The C# Backend API
  - type: web
    name: my-project-api
    runtime: docker
    # Tells Render to build from the ProjectManagerAPI subfolder
    dockerContext: ProjectManagerAPI 
    # NOTE: You MUST use a paid plan. Docker is not on the free plan.
    plan: starter 

  # Service 2: The React Frontend
  - type: static
    name: my-project-ui
    plan: free
    # Tells Render to build from the project-manager-ui subfolder
    rootDir: project-manager-ui
    buildFilter: # Optional: only rebuilds when frontend files change
      paths:
        - project-manager-ui/**
    buildCommand: npm install && npm run build
    publishDir: build